export const FETCH_FX_RATE = "FETCH_FX_RATE";
export const FETCH_INDEX = "FETCH_INDEX";

export const FETCH_STOCK_PRICE_CARD = "FETCH_STOCK_PRICE_CARD";
export const FETCH_INDIVIDUAL_STOCK = "FETCH_INDIVIDUAL_STOCK";
export const FETCH_INDIVIDUAL_STOCK_ERROR = "FETCH_INDIVIDUAL_STOCK_ERROR";

export const FETCH_DISCOUNT_CARD = "FETCH_DISCOUNT_CARD";
export const FETCH_DISCOUNT = "FETCH_DISCOUNT";

export const FETCH_CRYPTO_CARD = "FETCH_CRYPTO_CARD";
export const FETCH_CRYPTO = "FETCH_CRYPTO";

export const FETCH_CURRENCY_CARD = "FETCH_CURRENCY_CARD";
export const FETCH_CURRENCY = "FETCH_CURRENCY";
